name: Build and Deploy OCI Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: chussenot/steampipe-plugin-build-push-action@v0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"